# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ThriftTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThriftTutorial
  pod 'Thrift', :git => 'https://github.com/apache/thrift.git', :tag => 'v0.13.0'
  pod 'SwiftSocket'

end
