/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thrifttutorial;

import org.apache.thrift.TException;
import org.apache.thrift.protocol.TBinaryProtocol;
import org.apache.thrift.protocol.TJSONProtocol;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.protocol.TSimpleJSONProtocol;
import org.apache.thrift.transport.TSocket;
import org.apache.thrift.transport.TTransport;
import tutorial.Calculator;
import tutorial.Operation;
import tutorial.Work;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws TException {
        // Open a transport to the server
        TTransport transport = new TSocket("188.166.236.26", 9090);
        transport.open();

        // Declare the protocol to use
        TProtocol protocol = new TBinaryProtocol(transport);

        Calculator.Client client = new Calculator.Client(protocol);
        client.ping();
        System.out.println("ping!");
        System.out.println("1+2=" + client.add(1,2));
        System.out.println("100/10=" + client.calculate(0, new Work(100,10, Operation.DIVIDE)));

        transport.close();
        System.out.println("Fininshed");
    }
}
